name: Compare functions
on: push
jobs:
  compare:
    runs-on: ubuntu-latest
    steps: 
      - run: printenv | grep '_FUNC'
        env:
          CONTAINS_FUNC: ${{ contains('Hello', 'ell' ) }}     #「ell」を含むか
          STRART_WITH_FUNC: ${{ startsWith('Hello', 'He') }}  #「He」ではじまるか
          ENDS_WITH_FUNC: ${{ endsWith('Hello', 'lo') }}      #「lo」でおわるか